#define xffm_VERSION_MAJOR @xffm_VERSION_MAJOR@
#define xffm_VERSION_MINOR @xffm_VERSION_MINOR@
#define VERSION "@xffm_VERSION_MAJOR@.@xffm_VERSION_MINOR@"
#define PREFIX "@CMAKE_INSTALL_PREFIX@"
#define PACKAGE_LOCALE_DIR "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LOCALEDIR@"

#define SIGNAL_H @SIGNAL_H@
#define HAVE_GREP @HAVE_GREP@

