#define xffm_VERSION_MAJOR @xffm_VERSION_MAJOR@
#define xffm_VERSION_MINOR @xffm_VERSION_MINOR@
#define VERSION "@xffm_VERSION_MAJOR@.@xffm_VERSION_MINOR@"
#define PREFIX "@CMAKE_INSTALL_PREFIX@"
#define PACKAGE_LOCALE_DIR "@CMAKE_INSTALL_PREFIX@/@CMAKE_INSTALL_LOCALEDIR@"

#define @SIGNAL_H@
#define @MAGIC_H@
#define @READLINE_HISTORY_H@
#define @HAVE_GREP@
#define @HAVE_EMERGE@
#define @HAVE_PACMAN@
#define @HAVE_PKG@
#define @HAVE_LIBXML2@
#define @LIBMAGIC@
#define @MIMETYPE_PROGRAM@
#define @FREEDESKTOP_GLOBS@
#define @FREEDESKTOP_ALIAS@
#define @FREEDESKTOP_ICONS@

// FIXME: determine whether these are valid:
#define HAVE_STRUCT_DIRENT_D_TYPE 1
#define HAVE_FPATHCONF
#define HAVE_DIRFD

