#!/usr/bin/perl
if (not $ARGV[0]) {print "target directory not specified\n"; exit(1)}
$tgt = $ARGV[0];
if (not -d $tgt){print "$tgt is not a directory"; exit(1)}
#print `mkdir tgt`;
@dirs = ("cmake", "po", "xffm", "structure");
@files = ("COPYING", "INSTALL", "README", "CMakeLists.txt", "config.h.cmake");
foreach $dir (@dirs) { print `rsync -av $dir/ $tgt/$dir/`}
foreach $file (@files) { print `rsync -av $file $tgt/`}

