#ifndef ICON_MACROS
#define ICON_MACROS

#define GREENBALL "greenball"
#define REDBALL "redball"
#define GRAYBALL "grayball"
#define CANCEL "cancel"
#define EXECUTE "execute"

#define DEFAULT_ICON "text-x-generic"
#define USER_HOME "user-home"
#define FOLDER "folder"
#define DRIVE_HARDDISK "drive-harddisk-symbolic"
#define INPUT_KEYBOARD_SYMBOLIC "input-keyboard-symbolic"
#define NETWORK_WIRED_SYMBOLIC "network-wired-symbolic"
#define IMAGE_X_GENERIC "image-x-generic-symbolic"
#define ACCESSORIES_TEXT_EDITOR "document-edit-symbolic"
#define UTILITIES_TERMINAL "utilities-terminal-symbolic"
#define WINDOW_NEW "window-new-symbolic"
#define WINDOW_CLOSE "window-close-symbolic"
#define DIALOG_WARNING "dialog-warning"
#define APPLICATIONS_GRAPHICS "applications-graphics-symbolic"
#define SEARCH "system-search-symbolic"
#define BOOKMARK_NEW "bookmark-new-symbolic"
#define INSERT_OBJECT "insert-object-symbolic"
#define APPLICATION_X_EXECUTABLE "application-x-executable-symbolic"
#define GO_UP_SYMBOLIC "go-up-symbolic"
#define GO_UP "go-up-symbolic"
#define GO_HOME "go-home-symbolic"
#define APPLICATION_EXIT "application-exit-symbolic"
#define SYSTEM_RUN "system-run"
#define FILE_MANAGER "system-file-manager-symbolic"
#define PROCESS_STOP "process-stop-symbolic"
#define TAB_NEW "tab-new-symbolic"

#define LIST_ADD "list-add"
#define LIST_REMOVE "list-remove"

#define PACKAGE_X_GENERIC "package-x-generic"

#define EDIT_CLEAR "edit-clear-all-symbolic"
#define EDIT_CUT "edit-cut-symbolic"
#define EDIT_COPY "edit-copy-symbolic"
#define EDIT_PASTE "edit-paste-symbolic"
#define EDIT_DELETE "edit-delete-symbolic"

#define OPEN "open"
#define DOCUMENT_OPEN "folder-open"
#define DOCUMENT_NEW "document-new"
#define DOCUMENT_REVERT "document-revert-symbolic"
#define DOCUMENT_SAVE "document-save-symbolic"
#define DOCUMENT_PROPERTIES "document-properties-symbolic"

#define SYMLINK "emblem-symbolic-link"
#define EMBLEM_DOCUMENTS "emblem-documents-symbolic"
#define EMBLEM_UNREADABLE "emblem-unreadable"

//#define  ""
//#define XFFM_ICON "emblem-bsd"
#define XFFM_ICON "rodent_logo"
#define FSTAB_ICON "drive-harddisk-symbolic/SE/media-eject-symbolic/2.0/225"
#define EFS_ICON "drive-harddisk-symbolic/SE/emblem-readonly/2.0/225"
#define HOME_ICON "go-home-symbolic"
#define TRASH_ICON "user-trash-symbolic"
#define TRASH_FULL_ICON "user-trash-full"

#define HIGHLIGHT_EMBLEM "NE/" DOCUMENT_OPEN "/2.5/220"
#define HIGHLIGHT_TEXT "NE/" ACCESSORIES_TEXT_EDITOR "/2.5/220"
#define HIGHLIGHT_APP "NE/" APPLICATION_X_EXECUTABLE "/2.5/220"
#define HIGHLIGHT_UP GO_UP "/NW/" GO_UP_SYMBOLIC "/2.0/225"

//#define HIGHLIGHT_EMBLEM "NE/document-open/2.5/220"
//#define HIGHLIGHT_TEXT "NE/accessories-text-editor/2.5/220"
//#define HIGHLIGHT_APP "NE/application-x-executable/2.5/220"
//#define HIGHLIGHT_UP "go-up/NW/go-up-symbolic/2.0/225"

#endif
