#ifndef ICON_MACROS
#define ICON_MACROS

#define GO_UP "go-up"
#define EMBLEM_LOCK "emblem-lock"
#define EMBLEM_BOOKMARK "emblem-bookmark"
//#define SEARCH "edit-find"
#define OPEN_TERMINAL "video-display"
#define GO_HOME "emblem-go-home"
#define DOCUMENT_PROPERTIES "document-properties"
#define WINDOW_SHUTDOWN "system-shutdown-symbolic"
//#define WINDOW_CLOSE "process-stop-symbolic"
#define WINDOW_CLOSE "window-close"
#define HARD_DISK "drive-harddisk"

// File type emblems


#define GRAYBALL "emblem-grayball"
//#define CANCEL "cancel" // remove
#define EMBLEM_CANCEL "cancel" 
#define EXECUTE "execute"


#define EMBLEM_P "emblem-p"
#define EMBLEM_C "emblem-c"
#define EMBLEM_CC "emblem-cc"
#define EMBLEM_I "emblem-i"
#define EMBLEM_H "emblem-h"
#define EMBLEM_HH "emblem-hh"
#define EMBLEM_F "emblem-f"
#define EMBLEM_O "emblem-o"
#define EMBLEM_M "emblem-m"

#define EMBLEM_MSOFFICE "emblem-msoffice"
#define EMBLEM_PREFERENCES "emblem-preferences"
#define EMBLEM_LOG "emblem-about"
#define EMBLEM_TEXT "emblem-text"
#define EMBLEM_OO "emblem-oo"
#define EMBLEM_MATH "emblem-math"
#define EMBLEM_COMPRESSED "emblem-compressed"
#define EMBLEM_HIDDEN "emblem-show-hidden"
#define EMBLEM_FLOPPY "emblem-floppy"
#define EMBLEM_DESCENDING "emblem-descending"
#define EMBLEM_PACKAGE "emblem-compressed"
#define EMBLEM_INFO "emblem-about"
#define EMBLEM_AUTHENTICATION "emblem-keyhole"
#define EMBLEM_KEYBOARD "emblem-keyboard"
#define EMBLEM_TTY "emblem-tty"
#define EMBLEM_CLOSE "close"
#define EMBLEM_NO "no"
#define EMBLEM_APPLY "apply"
#define EMBLEM_ADD "emblem-add"
#define EMBLEM_REMOVE "emblem-remove"
#define EMBLEM_DELETE "emblem-delete"

// Menu icons
#define EMBLEM_ERROR "emblem-error"
#define EMBLEM_WARNING "emblem-warning"
#define EMBLEM_QUESTION "emblem-question"
#define EMBLEM_EXIT "emblem-exit"
#define EMBLEM_BLOWFISH "emblem-blowfish"
#define EMBLEM_EDIT "emblem-edit"
#define EMBLEM_GRAY_BALL "emblem-grayball"
#define EMBLEM_GREEN_BALL "emblem-greenball"
#define EMBLEM_RED_BALL "emblem-redball"
#define EMBLEM_NOACCESS "emblem-noaccess"
#define EMBLEM_NEW_TAB "list-add-symbolic"
#define EMBLEM_RUN "emblem-run"
#define EMBLEM_SYMLINK "emblem-link"
#define EMBLEM_SAVE "document-save"
#define EMBLEM_SAVE_AS "document-save-as"
#define EMBLEM_PROPERTIES "properties"
#define EMBLEM_COPY "edit-copy-symbolic"
#define EMBLEM_CUT "edit-cut-symbolic"
#define EMBLEM_PASTE "edit-paste-symbolic"
#define EMBLEM_FAVOURITE "emblem-favourite"
#define EMBLEM_GRAPHICS "emblem-graphics"
#define EMBLEM_UNDO "edit-undo"
#define EMBLEM_CLEAR "emblem-clear"
#define EMBLEM_SELECT_ALL "emblem-select-all"
#define EMBLEM_BOOKMARK "emblem-bookmark"
#define EMBLEM_TOGGLE "emblem-toggle"
#define EMBLEM_TRASH_FULL "user-trash-full"
#define EMBLEM_IMPORTANT "emblem-important"
#define EMBLEM_NEW_WINDOW "emblem-run"
#define EMBLEM_COLOR "emblem-color"
//#define EMBLEM_APPLY "ok"
#define EMBLEM_ABOUT "emblem-about"
#define EMBLEM_BROKEN "emblem-broken"
#define EMBLEM_START_HERE "emblem-start-here"
#define EMBLEM_BAK "emblem-bak"
#define EMBLEM_TERMINAL "emblem-terminal"
#define EMBLEM_ABOUT "emblem-about"
#define EMBLEM_INVERT "emblem-invert"
#define EMBLEM_TOGGLE "emblem-toggle"
#define EMBLEM_FOLDER_OPEN "emblem-folder"
#define EMBLEM_RESET "process-reset"
#define EMBLEM_FIND "emblem-find"
//#define EMBLEM_ "emblem-"

#define LIST_ADD "list-add"
#define OPEN_MENU "open-menu"




#endif
