.TH man 1 "06 May 2013" "" "Rodent-fgr man page"
.SH NAME
Rodent-fgr \- Graphic interface to the fgr command.
.
.SH SYNOPSIS
Rodent-fgr is graphic interface to the fgr command. With this utility, you can perform searches based on content or file attributes.  
.SH SEE ALSO
    fgr(1)
    http://sf.net/projects/xffm/
.SH BUGS
    Find any?
    Prompt response at https://sourceforge.net/p/xffm/bugs/milestone/rodent-fgr/
.
.SH AUTHOR
   Edscott Wilson Garcia <edscott@imp.mx>.
.SH COPYRIGHT
   GPLv3.
