find_program(AUTOTOOLS aclocal)
if (NOT AUTOTOOLS)
	message(FATAL_ERROR, "To build xffm+ you also need aclocal (from automake package).")
	return()
endif()

find_program(AUTOMAKE automake)
if (NOT AUTOMAKE)
	message(FATAL_ERROR, "To build xffm+ you also need automake.")
	return()
endif()
find_program(AUTOHEADER autoheader)
if (NOT AUTOHEADER)
	message(FATAL_ERROR, "To build xffm+ you also need autoheader.")
	return()
endif()
find_program(AUTOCONF autoconf)
if (NOT AUTOCONF)
	message(FATAL_ERROR, "To build xffm+ you also need autoconf.")
	return()
endif()

