
message(STATUS "Checking for readline/history.h...")
find_path(READLINE_HISTORY_H  NAMES readline/history.h )
if(NOT READLINE_HISTORY_H)
    set(READLINE_HISTORY_H "READLINE_HISTORY_H_NOTFOUND")
    message( STATUS "readline/history.h is not found" )
else()
    set(READLINE_HISTORY_H "HAVE_READLINE_HISTORY_H 1")
    message( STATUS  "readline/history.h was found." )
endif()
message(STATUS "Checking for signal.h...")
find_path(SIGNAL_H  NAMES signal.h )
if(NOT SIGNAL_H)
    set(SIGNAL_H "SIGNAL_H_NOTFOUND")
    message( STATUS "signal.h is not found" )
else()
    set(SIGNAL_H "HAVE_SIGNAL_H 1")
    message( STATUS  "signal.h was found." )
endif()

message(STATUS "Checking for signal.h...")
find_path(SIGNAL_H  NAMES signal.h )
if(NOT SIGNAL_H)
    set(SIGNAL_H "SIGNAL_H_NOTFOUND")
    message( STATUS "signal.h is not found" )
else()
    set(SIGNAL_H "HAVE_SIGNAL_H 1")
    message( STATUS  "signal.h was found." )
endif()

message(STATUS "Checking for magic.h...")
find_path(MAGIC_H  NAMES magic.h )
if(NOT MAGIC_H)
    set(MAGIC_H "MAGIC_H_NOTFOUND")
    message( STATUS "magic.h is not found" )
else()
    set(MAGIC_H "HAVE_MAGIC_H 1")
    message( STATUS  "magic.h was found." )
endif()

