
find_package(LibXml2 2.9.8 )
find_program(HAVE_LIBXML2 xmllint )
if(NOT HAVE_LIBXML2)
    set(HAVE_LIBXML2 "HAVE_LIBXML2_NOTFOUND")
    message( WARNING "LibXml2 not found: Software Updater will not be built." )
else()
    set(HAVE_LIBXML2 "HAVE_LIBXML2 1")
    message( STATUS "LibXml2 was found." )


    message(STATUS "Checking for pacman command...")
    find_program(HAVE_PACMAN pacman )
    if(NOT HAVE_PACMAN)
	set(HAVE_PACMAN "HAVE_PACMAN_NOTFOUND")
	message( STATUS "pacman is not found" )
	message(STATUS "Checking for emerge command...")
	find_program(HAVE_EMERGE emerge )
	if(NOT HAVE_EMERGE)
	    set(HAVE_EMERGE "HAVE_EMERGE_NOTFOUND")
	    message( STATUS "emerge is not found" )
	    message(STATUS "Checking for pkg command...")
	    find_program(HAVE_PKG pkg )
	    if(NOT HAVE_PKG)
		set(HAVE_PKG "HAVE_PKG_NOTFOUND")
		message( STATUS "pkg is not found" )
	    else()
		set(HAVE_PKG "HAVE_PKG 1")
		message( STATUS "Software Updater will be built for pkg." )
	    endif()
	else()
	    set(HAVE_PKG "PKG_SKIPPED")
	    set(HAVE_EMERGE "HAVE_EMERGE 1")
	    message( STATUS "Software Updater will be built for emerge." )
	endif()
    else()
	set(HAVE_PACMAN "HAVE_PACMAN 1")
	set(HAVE_EMERGE "EMERGE_SKIPPED")
	set(HAVE_PKG "PKG_SKIPPED")
	message( STATUS "Software Updater will be built for pacman." )
    endif()


endif()
# mimeinfo is now replaced by dev-perl/File-MimeInfo
message(STATUS "Checking for libmagic...")
find_library(LIBMAGIC NAMES libmagic.so)
if(NOT LIBMAGIC)
    set(LIBMAGIC "LIBMAGIC_NOTFOUND")
    message( WARNING "*** libmagic is not found: Look for it in *file* package." )
else()
    set(LIBMAGIC "HAVE_LIBMAGIC 1")
    set(LIBMAGIC_LIBRARIES "-lmagic")
    message(STATUS "libmagic was found." )
endif()

